SET search_path TO nounous;


-- Schéma

DROP SCHEMA IF EXISTS nounous CASCADE;
CREATE SCHEMA nounous AUTHORIZATION nounous;
GRANT ALL PRIVILEGES ON SCHEMA nounous TO nounous;


-- Tables

CREATE TABLE compte (
	IdCompte		INT			 	NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
	Pseudo			VARCHAR(25)		NOT NULL,
	MotDePasse		VARCHAR(25) 	NOT NULL,
	Email			VARCHAR(100)	NOT NULL,
	PRIMARY KEY (IdCompte)
);
CREATE UNIQUE INDEX idx_compte_pseudo ON compte (Pseudo ASC);

CREATE TABLE role (
	IdCompte		INT				NOT NULL,
	Role			VARCHAR(20)		NOT NULL,
	CHECK( Role IN ('ADMINISTRATEUR','UTILISATEUR', 'PARENT', 'NOUNOU') ),	
	FOREIGN KEY (IdCompte) REFERENCES compte (IdCompte),
	PRIMARY KEY (IdCompte, Role)
);

CREATE TABLE categorie (
	IdCategorie		INT				NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
	Libelle			VARCHAR(25)		NOT NULL,
	PRIMARY KEY (IdCategorie)
);

CREATE TABLE personne (
	IdPersonne		INT				NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
	IdCategorie		INT				NOT NULL,
	Nom				VARCHAR(25)  	NOT NULL,
	Prenom			VARCHAR(25) 	NOT NULL,
	FOREIGN KEY (IdCategorie) REFERENCES categorie (IdCategorie),
	PRIMARY KEY (IdPersonne)
);

CREATE TABLE telephone (
	IdTelephone		INT				NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
	IdPersonne		INT			 	NOT NULL,
	Libelle			VARCHAR(25)		NOT NULL,
	Numero			VARCHAR(25)		NOT NULL,
	FOREIGN KEY (IdPersonne) REFERENCES personne (IdPersonne),
	PRIMARY KEY (IdTelephone)
);

CREATE TABLE parent (
	IdParent		INT				NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
	Firstname VARCHAR(25) NOT NULL,
	Lastname VARCHAR(25) NOT NULL,
	Adresse		VARCHAR(250),
	Phone		VARCHAR(25),
	IdCompte	INT NOT NULL,
	FOREIGN KEY (IdCompte) REFERENCES compte (IdCompte),
	PRIMARY KEY (IdParent)
);

CREATE TABLE nounou (
	IdNounou		INT				NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
	Firstname VARCHAR(25) NOT NULL,
	Lastname VARCHAR(25) NOT NULL,
	Adresse		VARCHAR(250),
	Phone		VARCHAR(25),
	IdCompte	INT NOT NULL,
	FOREIGN KEY (IdCompte) REFERENCES compte (IdCompte),
	PRIMARY KEY (IdNounou)
);

CREATE TABLE enfant (
	IdEnfant		INT				NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
	Firstname VARCHAR(25) NOT NULL,
	Lastname VARCHAR(25) NOT NULL,
	DateNaissance		Date			 	NOT NULL,
	IdParent INT NOT NULL,
	FOREIGN KEY (IdParent) REFERENCES parent (IdParent),
	PRIMARY KEY (IdEnfant)
);

CREATE TABLE contrat (
	IdContrat		INT				NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
	DateDebut		Date			 	NOT NULL,
	DateFin			Date		NOT NULL,
	TarifHoraire			numeric(10,2),
	indemRepas			numeric(10,2),
	IdNounou INT NOT NULL,
	IdEnfant INT NOT NULL,
	FOREIGN KEY (IdNounou) REFERENCES nounou (IdNounou),
	FOREIGN KEY (IdEnfant) REFERENCES enfant (IdEnfant),
	PRIMARY KEY (IdContrat)
);

CREATE TABLE garder (
	IdGarder		INT				NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
	HeureDebut		TIME			NOT NULL,
	HeureFin		TIME			NOT NULL,
	aMange			BOOLEAN 		NOT NULL,
	dateJ 			DATE,
	IdContrat 		INT 			NOT NULL,
	indemniteEntretien NUMERIC(10,2),
	FOREIGN KEY (IdContrat) REFERENCES contrat (IdContrat),
	PRIMARY KEY (IdGarder)
);


